//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sampler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export audio to
        ///{0}.
        /// </summary>
        internal static string Could_not_export_audio_to {
            get {
                return ResourceManager.GetString("Could_not_export_audio_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export chart image to
        ///{0}.
        /// </summary>
        internal static string Could_not_export_chart_image_to {
            get {
                return ResourceManager.GetString("Could_not_export_chart_image_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open sample file at
        ///{0}.
        /// </summary>
        internal static string Could_not_open_sample_file_at {
            get {
                return ResourceManager.GetString("Could_not_open_sample_file_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save sample to
        ///{0}.
        /// </summary>
        internal static string Could_not_save_sample_to {
            get {
                return ResourceManager.GetString("Could_not_save_sample_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        internal static string Do_you_want_to_save_your_changes_ {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_your_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting temporary audio file at
        ///{0}.
        /// </summary>
        internal static string Error_while_deleting_temporary_audio_file_at {
            get {
                return ResourceManager.GetString("Error_while_deleting_temporary_audio_file_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving the program&apos;s base path..
        /// </summary>
        internal static string Error_while_retrieving_the_programs_base_path {
            get {
                return ResourceManager.GetString("Error_while_retrieving_the_programs_base_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help files not available - they should be located in the Help folder that should come with Sampler.exe.
        /// </summary>
        internal static string Help_files_not_available {
            get {
                return ResourceManager.GetString("Help_files_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to be a valid function.  Read the function manual for more help.
        ///{0}.
        /// </summary>
        internal static string This_does_not_appear_to_be_a_valid_function {
            get {
                return ResourceManager.GetString("This_does_not_appear_to_be_a_valid_function", resourceCulture);
            }
        }
    }
}
